### ISSUE TITLE
could you make a flatpak for lyrics?

### ISSUE THREAD

**Issue by chemel9** [naaando/lyrics#15]
Hi, I really appreciate your work , is a very good application
but i don't use elementary OS
could you make a flatpak for lyrics?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by naaando** [comment]
Hm, I accomplished the packaging of the lyrics app for flatpak, but I'm struggling to find a way to bypass dbus naming ownership for lyricsources (a python app that find/downloads the lyrics and communicate with the main app though DBus).

BTW, what distro do you use?

**Comment by chemel9** [comment]
i use linux deepin. ;)

**Comment by naaando** [comment]
Well, you should be able to install it using the debian packages I provide on the release tab.

I'm marking this as blocked while I don't have an alternative to [lyricsources](https://github.com/naaando/lyricsources), as I said I had managed to package the app but without a source it ain't useful. 

I'm considering use another solution to fetch the lyrics because lyricsources has some problems for my use cases, it was developed to download, save and track lyric files, along with player tracking, think of some kind of core for managing lrc files, but I'm currently using it just for downloading lyrics. Although it has a very good code it is a bit outdated using python 2 and I don't want to maintain this.

**Comment by naaando** [comment]
It's not feasible to do right now unfortunately. But I can remove this dependency as I was considering already and test on a vm to guarantee that you should be able to install it. But I can't make a flatpak and I won't fix something that I'll stop using.

**Comment by chemel9** [comment]
oh thank you so much.
thanks for your time
i could install it :) , it worked

maybe in the future,you can make a flatpak.

**Comment by naaando** [comment]
I'm porting lyricsources to Vala, I believe soon I'll be able to release flatpaks

**Comment by naaando** [comment]
Almost done. Just waiting review from https://github.com/flathub/flathub/pull/908

**Comment by chemel9** [comment]
Thank you :)

**Comment by naaando** [comment]
- [x] Flatpak manifest
- [x] Publish on flathub
